package:
  name: expat
  version: 2.4.8
  epoch: 0
  description: "XML SAX Parser library written in C"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage2
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage2/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base

pipeline:
  - uses: fetch
    with:
      uri: https://downloads.sourceforge.net/project/expat/expat/${{package.version}}/expat-${{package.version}}.tar.bz2
      expected-sha256: a247a7f6bbb21cf2ca81ea4cbb916bfb9717ca523631675f99b3d4a5678dcd16
  - name: Configure
    runs: |
      ./configure \
         --host=$(uname -m)-pc-linux-gnu \
         --target=$(uname -m)-pc-linux-gnu \
         --prefix=/usr \
         --datadir=/usr/share
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
